# Generated by Django 5.1.4 on 2024-12-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nobility',
            field=models.IntegerField(choices=[(0, 'King'), (1, 'Archduke'), (2, 'Prince'), (3, 'Duke'), (4, 'Marquess'), (5, 'Count'), (6, 'Viscount'), (7, 'Baron'), (8, 'Citizen'), (9, 'Stateless')], default=7),
        ),
    ]
